#
# path to external tools used by the test suite
#

# gezel simulators

FDLSIM=/home/schaum/gezel2/sim/build/bin/fdlsim
GPLATFORM=/home/schaum/gezel2/sim/build/bin/gplatform

# gezel code generators (not included in simulator release)

FDLVHD=/home/schaum/gezel2/cgen/build/bin/fdlvhd

# installation directory for systemc

SYSTEMC=/opt/systemc-2.1.v1

# java compiler

JAVAC=/opt/IBMJava2-142/bin/javac
JAVA=/opt/IBMJava2-142/bin/java

# AVRORA AVR-ISS

AVRORACLS=/opt/avrora-1.4/bin

# Small Devices C Compiler (sdcc)

SDCC=/opt/sdcc-2.5/bin/sdcc

# arm-linux C compiler

ARMCC=/opt/arm-linux-3.2/bin/arm-linux-gcc
