#
# path to external tools used by the test suite
#

# gezel simulators

FDLSIM=/opt/gezel/bin/fdlsim
GPLATFORM=/opt/gezel/bin/gplatform
#GPLATFORM=~/gezelSVN/gezel2/sim/build/bin/gplatform
FDLLIB=/opt/gezel/lib
FDLINC=/opt/gezel/include/gezel
PICOASM=/opt/KCPSM3/dosemu/picoasm

# gezel code generators (not included in simulator release)

FDLVHD=/opt/gezel/bin/fdlvhd

# arm-linux C compiler

ARMCC=/usr/local/arm/bin/arm-linux-gcc

# small devices C compiler

SDCC=sdcc
# AVR C compiler & exec generator
AVRGCC=avr-gcc
AVROBJDUMP=avr-objdump
AVROBJCOPY=avr-objcopy
