#
# path to external tools used by the test suite
#

# gezel simulators

FDLSIM          ?= $(abs_top_builddir)/standalone/fdlsim$(EXEEXT)
GPLATFORM       ?= $(abs_top_builddir)/gplatform/gplatform$(EXEEXT)
FDLLIB          ?= /opt/gezel/lib
FDLINC          ?= /opt/gezel/include/gezel
PICOASM         ?= /opt/KCPSM3/dosemu/picoasm

# gezel code generators (not included in simulator release)

FDLVHD          ?= /opt/gezel/bin/fdlvhd


# ARM Linux C compiler

ARMCC           ?= arm-linux-gnu-gcc
ARMASFLAGS      ?=
ARMCFLAGS       ?= -Os
ARMLDFLAGS      ?= -static


# AVR C compiler & exec generator

AVRGCC          ?= avr-gcc
AVROBJDUMP      ?= avr-objdump
AVROBJCOPY      ?= avr-objcopy
AVRMCU          ?= atmega128
AVRCFLAGS       ?= -Os -mmcu=$(AVRMCU)
AVRLIBS         ?=


# Xilinx picoblaze compiler/assembler

PICOAS          ?= picoasm
PICOASFLAGS     ?=


# small devices C compiler

SDCC            ?= sdcc
SDCCCFLAGS      ?=

.PHONY: clean-sdcc
clean-sdcc:
	rm -f *~ *.asm *.lnk *.map *.rel *.sym *.rst *.mem *.ihx *.lst *.lk


# Java compiler

JAVACFLAGS      ?= -classpath $(abs_top_builddir)/java
JAVAFLAGS       ?= -classpath $(abs_top_builddir)/java:.
JAVASIM         ?= LD_LIBRARY_PATH=$(abs_top_builddir)/gezel/.libs:$(abs_top_builddir)/ipblock/.libs:$(abs_top_builddir)/java/.libs $(JAVA) $(JAVAFLAGS)

.PHONY: clean-java
clean-java:
	rm -f *.class
