# $Id: Makefile,v 1.1.1.1 2005/07/14 17:32:45 schaum Exp $

all:
	cd ./counter1; make ; cd .
	cd ./counter2; make ; cd .
	cd ./counter3; make ; cd .
	cd ./euclid; make ; cd .
	cd ./avrora2; make ; cd .
	cd ./avrora1; make ; cd .

sim:
	cd ./counter1; make sim; cd .
	cd ./counter2; make sim; cd .
	cd ./counter3; make sim; cd .
	cd ./euclid; make sim; cd .
	cd ./avrora2; make sim; cd .
	cd ./avrora1; make sim; cd .

clean:
	cd ./counter1; make clean; cd .
	cd ./counter2; make clean; cd .
	cd ./counter3; make clean; cd .
	cd ./euclid; make clean; cd .
	cd ./avrora2; make clean; cd .
	cd ./avrora1; make clean; cd .
