/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GezelModule */

#ifndef _Included_GezelModule
#define _Included_GezelModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GezelModule
 * Method:    loadfile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GezelModule_loadfile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     GezelModule
 * Method:    tick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GezelModule_tick
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
