/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GezelInport */

#ifndef _Included_GezelInport
#define _Included_GezelInport
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: glbPortId */
/*
 * Class:     GezelInport
 * Method:    portname
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GezelInport_portname
  (JNIEnv *, jobject, jstring);

/*
 * Class:     GezelInport
 * Method:    write
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GezelInport_write
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
