/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GezelOutport */

#ifndef _Included_GezelOutport
#define _Included_GezelOutport
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: glbPortId */
/*
 * Class:     GezelOutport
 * Method:    portname
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GezelOutport_portname
  (JNIEnv *, jobject, jstring);

/*
 * Class:     GezelOutport
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GezelOutport_read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
