# $Id: Makefile,v 1.1.1.1 2005/07/14 17:32:44 schaum Exp $

all:
	cd ./arm2arm;             make ; cd .
	cd ./hello51;    	  make ; cd .
	cd ./gfmul;      	  make ; cd .
	cd ./helloarm;   	  make ; cd .
	cd ./aesarm;     	  make ; cd .
	cd ./cyclecount; 	  make ; cd .
	cd ./euclid;     	  make ; cd .
	cd ./ssidehsk;   	  make ; cd .
	cd ./aes8051;	 	  make ; cd .
	cd ./diblaze;	 	  make ; cd .
	cd ./euclid;	 	  make ; cd .
	cd ./pblaze;	 	  make ; cd .
	cd ./ramprobe;	 	  make ; cd .
	cd ./block8051;  	  make ; cd .
	cd ./armsfu;	 	  make ; cd .
	cd ./blockarm;   	  make ; cd .
	cd ./fslinterface;        make ; cd .
	cd ./fsl2;                make ; cd .
	cd ./xilinxfsl_single;    make ; cd .
	cd ./xilinxipiffifo;      make ; cd .
	cd ./xilinxipiffifo_gcd;  make ; cd .
	cd ./xilinxipifreg_gcd;   make ; cd .
	cd ./xilinxipifmem_gcd;   make ; cd .
	cd ./xilinxipifreg_sub64; make ; cd .
	cd ./cordicfsl;		  make ; cd .

sim:
	cd ./arm2arm;             make sim; cd .
	cd ./hello51;      	  make sim; cd .
	cd ./gfmul;        	  make sim; cd .
	cd ./helloarm;     	  make sim; cd .
	cd ./aesarm;       	  make sim; cd .
	cd ./cyclecount;   	  make sim; cd .
	cd ./euclid;       	  make sim; cd .
	cd ./ssidehsk;     	  make sim; cd .
	cd ./aes8051;	   	  make sim; cd .
	cd ./diblaze;	   	  make sim; cd .
	cd ./euclid;	   	  make sim; cd .
	cd ./pblaze;	   	  make sim; cd .
	cd ./ramprobe;	   	  make sim; cd .
	cd ./block8051;    	  make sim; cd .
	cd ./armsfu;	   	  make sim; cd .
	cd ./blockarm;     	  make sim; cd .
	cd ./fslinterface;        make sim; cd .
	cd ./fsl2;                make sim; cd .
	cd ./xilinxfsl_single;    make sim; cd .
	cd ./xilinxipiffifo;      make sim; cd .
	cd ./xilinxipiffifo_gcd;  make sim; cd .
	cd ./xilinxipifreg_gcd;   make sim; cd .
	cd ./xilinxipifmem_gcd;   make sim; cd .
	cd ./xilinxipifreg_sub64; make sim; cd .
	cd ./cordicfsl;		  make sim; cd .

clean:
	cd ./arm2arm;             make clean; cd .
	cd ./hello51;      	  make clean; cd .
	cd ./gfmul;        	  make clean; cd .
	cd ./helloarm;     	  make clean; cd .
	cd ./aesarm;       	  make clean; cd .
	cd ./cyclecount;   	  make clean; cd .
	cd ./euclid;       	  make clean; cd .
	cd ./ssidehsk;     	  make clean; cd .
	cd ./aes8051;	   	  make clean; cd .
	cd ./diblaze;	   	  make clean; cd .
	cd ./euclid;	   	  make clean; cd .
	cd ./pblaze;	   	  make clean; cd .
	cd ./diblaze;	   	  make clean; cd .
	cd ./ramprobe;	   	  make clean; cd .
	cd ./block8051;    	  make clean; cd .
	cd ./armsfu;	   	  make clean; cd .
	cd ./blockarm;     	  make clean; cd .
	cd ./fslinterface; 	  make clean; cd .
	cd ./fsl2;                make clean; cd .
	cd ./xilinxfsl_single;    make clean; cd .
	cd ./xilinxipiffifo;      make clean; cd .
	cd ./xilinxipiffifo_gcd;  make clean; cd .
	cd ./xilinxipifreg_gcd;   make clean; cd .
	cd ./xilinxipifmem_gcd;   make clean; cd .
	cd ./xilinxipifreg_sub64; make clean; cd .
	cd ./cordicfsl;		  make clean; cd .

